name: HTTP Request Action

on:
  push:
    branches: [develop]

jobs:
  deployment:
    runs-on: ubuntu-latest
    env:
      USER: ${{ github.event.head_commit.author.username }}
      TEXT: ${{ github.event.head_commit }}

    steps:
      - run: |
          SCORE=$(echo $TEXT | cut -d '|' -f 2)
          echo $SCORE
          echo $TEXT
          curl --data '{"user": $USER, "score": $SCORE}' --request POST https://wocleaderboard-backend.herokuapp.com/updateLeaderBoard/

#     - name: Deploy Stage
#       uses: fjogeleit/http-request-action@master
#       with:
#         url: 'https://wocleaderboard-backend.herokuapp.com/updateLeaderBoard/' # use the server url here
#         method: 'POST'
#         data: '{ "user":  "${{ github.event.pull_request.user.login }}" , "score": "${{ github.event.label.name }}" }'

