name: HTTP Request Action

on:
  push:
    branches: [ develop ]
  
jobs:
  deployment:
    runs-on: ubuntu-latest
    env:
      user: ${{ github.event.head_commit.author.username }}
      message: ${{ github.event.head_commit }}
      GITHUB_CONTEXT: ${{ toJson(github) }}
    steps:
      - run: |
          
          echo " hello worakdfsj asdklj ${{ github.event.pull_request.user.login }}"
          echo `env`
          SCORE=$(echo $message | cut -d '|' -f 2)
          echo $score
          curl --data '{"user": $user, "score": $SCORE}'
          
#     - name: Deploy Stage
#       uses: fjogeleit/http-request-action@master
#       with:
#         url: 'https://wocleaderboard-backend.herokuapp.com/updateLeaderBoard/' # use the server url here
#         method: 'POST'
#         data: '{ "user":  "${{ github.event.pull_request.user.login }}" , "score": "${{ github.event.label.name }}" }'

